# Simplified GoLangCI-Lint configuration
# Note: There are compatibility issues between Go 1.24.2 and golangci-lint v1.55.2
# The typecheck linter cannot be properly disabled, causing false "undefined" errors
# However, the code compiles successfully with `go build ./...`
# 
# Workaround: The Makefile lint target runs `go build` first to verify compilation

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 15

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/koopa0/assistant

  lll:
    line-length: 120

  misspell:
    locale: US

linters:
  disable:
    - typecheck  # Disabled due to Go 1.24.2 compatibility issues
  enable:
    # Essential linters only
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - lll

issues:
  exclude-dirs:
    - vendor
    - .git
    - bin
    - deployments
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  
  max-issues-per-linter: 0
  max-same-issues: 0