// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCausalLink(ctx context.Context, arg AddCausalLinkParams) (*EpisodicMemory, error)
	AddFavoriteTool(ctx context.Context, arg AddFavoriteToolParams) (*AddFavoriteToolRow, error)
	AddSkillLearningPoint(ctx context.Context, arg AddSkillLearningPointParams) (*UserSkill, error)
	// =====================================================
	// MEMORY LIFECYCLE OPERATIONS
	// =====================================================
	// Archives old memory entries by reducing their importance
	ArchiveOldMemoryEntries(ctx context.Context, arg ArchiveOldMemoryEntriesParams) (int64, error)
	// =====================================================
	// BATCH OPERATIONS FOR PERFORMANCE
	// =====================================================
	// Bulk insert memory entries for performance
	BatchCreateMemoryEntries(ctx context.Context, arg []BatchCreateMemoryEntriesParams) (int64, error)
	// Batch update access counts for multiple entries
	BatchIncrementMemoryAccess(ctx context.Context, ids []pgtype.UUID) error
	CleanupUnusedPatterns(ctx context.Context, arg CleanupUnusedPatternsParams) error
	ClearExpiredWorkingMemory(ctx context.Context) error
	ClearWorkingMemorySlot(ctx context.Context, arg ClearWorkingMemorySlotParams) error
	CompleteCollaboration(ctx context.Context, arg CompleteCollaborationParams) (*AgentCollaboration, error)
	// Semantic memories don't decay
	// Finds similar memory entries for consolidation
	ConsolidateMemoryEntries(ctx context.Context, arg ConsolidateMemoryEntriesParams) ([]*ConsolidateMemoryEntriesRow, error)
	ConsolidateWorkingMemory(ctx context.Context, arg ConsolidateWorkingMemoryParams) ([]*ConsolidateWorkingMemoryRow, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	// =====================================================
	// AGENT COLLABORATIONS QUERIES
	// =====================================================
	CreateAgentCollaboration(ctx context.Context, arg CreateAgentCollaborationParams) (*AgentCollaboration, error)
	// Agent collaboration queries
	// =====================================================
	// AGENT DEFINITIONS QUERIES
	// =====================================================
	CreateAgentDefinition(ctx context.Context, arg CreateAgentDefinitionParams) (*AgentDefinition, error)
	// Agent execution queries
	CreateAgentExecution(ctx context.Context, arg CreateAgentExecutionParams) (*AgentExecution, error)
	// Chain execution queries
	CreateChainExecution(ctx context.Context, arg CreateChainExecutionParams) (*ChainExecution, error)
	// =====================================================
	// CODE PATTERNS QUERIES
	// =====================================================
	CreateCodePattern(ctx context.Context, arg CreateCodePatternParams) (*CodePattern, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (*Conversation, error)
	// Development workflow queries
	// =====================================================
	// DEVELOPMENT SESSIONS QUERIES
	// =====================================================
	CreateDevelopmentSession(ctx context.Context, arg CreateDevelopmentSessionParams) (*DevelopmentSession, error)
	CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (*Embedding, error)
	// Advanced memory system queries
	// =====================================================
	// EPISODIC MEMORIES QUERIES
	// =====================================================
	CreateEpisodicMemory(ctx context.Context, arg CreateEpisodicMemoryParams) (*EpisodicMemory, error)
	// =====================================================
	// EVENT PROJECTIONS QUERIES
	// =====================================================
	CreateEventProjection(ctx context.Context, arg CreateEventProjectionParams) (*EventProjection, error)
	// =====================================================
	// KNOWLEDGE EDGES QUERIES
	// =====================================================
	CreateKnowledgeEdge(ctx context.Context, arg CreateKnowledgeEdgeParams) (*KnowledgeEdge, error)
	// =====================================================
	// KNOWLEDGE EVOLUTION QUERIES
	// =====================================================
	CreateKnowledgeEvolution(ctx context.Context, arg CreateKnowledgeEvolutionParams) (*KnowledgeEvolution, error)
	// Knowledge graph queries
	// =====================================================
	// KNOWLEDGE NODES QUERIES
	// =====================================================
	CreateKnowledgeNode(ctx context.Context, arg CreateKnowledgeNodeParams) (*KnowledgeNode, error)
	// =====================================================
	// AGENT KNOWLEDGE SHARING QUERIES
	// =====================================================
	CreateKnowledgeShare(ctx context.Context, arg CreateKnowledgeShareParams) (*AgentKnowledgeShare, error)
	// =====================================================
	// LEARNED PATTERNS QUERIES
	// =====================================================
	CreateLearnedPattern(ctx context.Context, arg CreateLearnedPatternParams) (*LearnedPattern, error)
	// Learning system queries
	// =====================================================
	// LEARNING EVENTS QUERIES
	// =====================================================
	CreateLearningEvent(ctx context.Context, arg CreateLearningEventParams) (*LearningEvent, error)
	// Creates a new memory entry with explicit column selection
	CreateMemoryEntry(ctx context.Context, arg CreateMemoryEntryParams) (*CreateMemoryEntryRow, error)
	// =====================================================
	// MEMORY RELATIONSHIPS AND GRAPH OPERATIONS
	// =====================================================
	// Creates a relationship between two memory entries
	CreateMemoryRelation(ctx context.Context, arg CreateMemoryRelationParams) (*MemoryRelation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (*CreateMessageRow, error)
	// =====================================================
	// PROCEDURAL MEMORIES QUERIES
	// =====================================================
	CreateProceduralMemory(ctx context.Context, arg CreateProceduralMemoryParams) (*ProceduralMemory, error)
	// =====================================================
	// SEMANTIC MEMORIES QUERIES
	// =====================================================
	CreateSemanticMemory(ctx context.Context, arg CreateSemanticMemoryParams) (*SemanticMemory, error)
	// System events and event sourcing queries
	// =====================================================
	// SYSTEM EVENTS QUERIES
	// =====================================================
	CreateSystemEvent(ctx context.Context, arg CreateSystemEventParams) (*SystemEvent, error)
	// Tool cache queries
	CreateToolCacheEntry(ctx context.Context, arg CreateToolCacheEntryParams) (*ToolCache, error)
	// Tools and tool execution related queries
	CreateToolExecution(ctx context.Context, arg CreateToolExecutionParams) (*ToolExecution, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	// User context queries
	CreateUserContext(ctx context.Context, arg CreateUserContextParams) (*UserContext, error)
	// User preferences queries
	CreateUserPreference(ctx context.Context, arg CreateUserPreferenceParams) (*UserPreference, error)
	// =====================================================
	// USER SKILLS QUERIES
	// =====================================================
	CreateUserSkill(ctx context.Context, arg CreateUserSkillParams) (*UserSkill, error)
	// =====================================================
	// WORKING MEMORY QUERIES
	// =====================================================
	CreateWorkingMemorySlot(ctx context.Context, arg CreateWorkingMemorySlotParams) (*WorkingMemory, error)
	DeactivateAgent(ctx context.Context, id pgtype.UUID) error
	DeactivateConflictingMemories(ctx context.Context, arg DeactivateConflictingMemoriesParams) error
	DeactivateKnowledgeEdge(ctx context.Context, id pgtype.UUID) error
	DeactivateKnowledgeNode(ctx context.Context, id pgtype.UUID) error
	DeactivatePattern(ctx context.Context, id pgtype.UUID) error
	DeactivateUser(ctx context.Context, id pgtype.UUID) (*DeactivateUserRow, error)
	DeleteAgentExecution(ctx context.Context, id pgtype.UUID) error
	DeleteChainExecution(ctx context.Context, id pgtype.UUID) error
	DeleteConversation(ctx context.Context, id pgtype.UUID) error
	DeleteDecayedMemories(ctx context.Context, arg DeleteDecayedMemoriesParams) error
	DeleteEmbedding(ctx context.Context, arg DeleteEmbeddingParams) error
	DeleteEmbeddingByID(ctx context.Context, id pgtype.UUID) error
	// Deletes expired memory entries and returns count
	DeleteExpiredMemoryEntries(ctx context.Context) (int64, error)
	DeleteExpiredToolCache(ctx context.Context) error
	DeleteExpiredUserContext(ctx context.Context) error
	// Deletes memory entries by user with optional filters
	DeleteMemoryEntriesByUser(ctx context.Context, arg DeleteMemoryEntriesByUserParams) (int64, error)
	// Deletes a memory entry by ID
	DeleteMemoryEntry(ctx context.Context, id pgtype.UUID) error
	DeleteMessage(ctx context.Context, id pgtype.UUID) error
	DeleteMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) error
	DeleteOldEvents(ctx context.Context, createdAt time.Time) error
	DeleteOldLearningEvents(ctx context.Context, arg DeleteOldLearningEventsParams) error
	DeleteOldSessions(ctx context.Context, arg DeleteOldSessionsParams) error
	DeleteOldToolExecutions(ctx context.Context, startedAt pgtype.Timestamptz) error
	DeleteToolCacheByUser(ctx context.Context, arg DeleteToolCacheByUserParams) error
	DeleteToolCacheEntry(ctx context.Context, id pgtype.UUID) error
	DeleteUserContext(ctx context.Context, arg DeleteUserContextParams) error
	DeleteUserContextByType(ctx context.Context, arg DeleteUserContextByTypeParams) error
	DeleteUserPreference(ctx context.Context, arg DeleteUserPreferenceParams) error
	DeleteUserPreferencesByCategory(ctx context.Context, arg DeleteUserPreferencesByCategoryParams) error
	EndDevelopmentSession(ctx context.Context, arg EndDevelopmentSessionParams) (*DevelopmentSession, error)
	EvolvePattern(ctx context.Context, arg EvolvePatternParams) (*CodePattern, error)
	ExtendWorkingMemoryExpiry(ctx context.Context, arg ExtendWorkingMemoryExpiryParams) (*WorkingMemory, error)
	FindDirectConnections(ctx context.Context, arg FindDirectConnectionsParams) ([]*FindDirectConnectionsRow, error)
	GetActiveCollaborations(ctx context.Context, dollar_1 pgtype.UUID) ([]*GetActiveCollaborationsRow, error)
	GetActiveSessions(ctx context.Context, dollar_1 pgtype.UUID) ([]*DevelopmentSession, error)
	GetActiveUsers(ctx context.Context, arg GetActiveUsersParams) ([]*GetActiveUsersRow, error)
	GetAgentCollaboration(ctx context.Context, id pgtype.UUID) (*GetAgentCollaborationRow, error)
	GetAgentCollaborations(ctx context.Context, arg GetAgentCollaborationsParams) ([]*GetAgentCollaborationsRow, error)
	GetAgentDefinition(ctx context.Context, id pgtype.UUID) (*AgentDefinition, error)
	GetAgentDefinitionByName(ctx context.Context, agentName string) (*AgentDefinition, error)
	GetAgentDefinitions(ctx context.Context, dollar_1 []string) ([]*AgentDefinition, error)
	GetAgentExecution(ctx context.Context, id pgtype.UUID) (*AgentExecution, error)
	GetAgentExecutionStats(ctx context.Context, arg GetAgentExecutionStatsParams) (*GetAgentExecutionStatsRow, error)
	GetAgentExecutionsByUser(ctx context.Context, arg GetAgentExecutionsByUserParams) ([]*AgentExecution, error)
	GetAgentPerformanceRankings(ctx context.Context, arg GetAgentPerformanceRankingsParams) ([]*GetAgentPerformanceRankingsRow, error)
	GetAgentsByCapability(ctx context.Context, capabilities []byte) ([]*AgentDefinition, error)
	GetAgentsByDomain(ctx context.Context, expertiseDomains []string) ([]*AgentDefinition, error)
	GetAllEmbeddingCount(ctx context.Context) (int64, error)
	GetAllEventProjections(ctx context.Context) ([]*EventProjection, error)
	GetAllMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]*GetAllMessagesByConversationRow, error)
	GetAllUserContext(ctx context.Context, dollar_1 pgtype.UUID) ([]*UserContext, error)
	GetAllUserPreferences(ctx context.Context, dollar_1 pgtype.UUID) ([]*UserPreference, error)
	GetAutomatableProcedures(ctx context.Context, arg GetAutomatableProceduresParams) ([]*ProceduralMemory, error)
	GetChainExecution(ctx context.Context, id pgtype.UUID) (*ChainExecution, error)
	GetChainExecutionStats(ctx context.Context, arg GetChainExecutionStatsParams) (*GetChainExecutionStatsRow, error)
	GetChainExecutionsByUser(ctx context.Context, arg GetChainExecutionsByUserParams) ([]*ChainExecution, error)
	GetCodePattern(ctx context.Context, id pgtype.UUID) (*CodePattern, error)
	GetCodePatterns(ctx context.Context, arg GetCodePatternsParams) ([]*CodePattern, error)
	// =====================================================
	// AGENT COLLABORATION ANALYTICS QUERIES
	// =====================================================
	GetCollaborationEfficiency(ctx context.Context, arg GetCollaborationEfficiencyParams) (*GetCollaborationEfficiencyRow, error)
	GetCollaborationStatistics(ctx context.Context, arg GetCollaborationStatisticsParams) (*GetCollaborationStatisticsRow, error)
	GetCollaborationTrends(ctx context.Context, arg GetCollaborationTrendsParams) ([]*GetCollaborationTrendsRow, error)
	GetCollaborationsByAgent(ctx context.Context, arg GetCollaborationsByAgentParams) ([]*GetCollaborationsByAgentRow, error)
	GetConnectedNodes(ctx context.Context, arg GetConnectedNodesParams) ([]*GetConnectedNodesRow, error)
	GetConversation(ctx context.Context, id pgtype.UUID) (*Conversation, error)
	GetConversationCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]*Conversation, error)
	GetDevelopmentSession(ctx context.Context, id pgtype.UUID) (*DevelopmentSession, error)
	GetDevelopmentSessions(ctx context.Context, arg GetDevelopmentSessionsParams) ([]*DevelopmentSession, error)
	GetEdgesByType(ctx context.Context, arg GetEdgesByTypeParams) ([]*GetEdgesByTypeRow, error)
	GetEmbedding(ctx context.Context, arg GetEmbeddingParams) (*Embedding, error)
	GetEmbeddingByID(ctx context.Context, id pgtype.UUID) (*Embedding, error)
	GetEmbeddingCount(ctx context.Context, contentType string) (int64, error)
	GetEmbeddingsByType(ctx context.Context, arg GetEmbeddingsByTypeParams) ([]*Embedding, error)
	GetEntityEvolutionHistory(ctx context.Context, dollar_1 pgtype.UUID) ([]*KnowledgeEvolution, error)
	GetEpisodicMemories(ctx context.Context, arg GetEpisodicMemoriesParams) ([]*EpisodicMemory, error)
	GetEpisodicMemory(ctx context.Context, id pgtype.UUID) (*EpisodicMemory, error)
	GetEventProjection(ctx context.Context, projectionName string) (*EventProjection, error)
	GetEventStatistics(ctx context.Context, arg GetEventStatisticsParams) (*GetEventStatisticsRow, error)
	GetEventsByAggregate(ctx context.Context, arg GetEventsByAggregateParams) ([]*SystemEvent, error)
	GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]*SystemEvent, error)
	GetExecutionTrends(ctx context.Context, arg GetExecutionTrendsParams) ([]*GetExecutionTrendsRow, error)
	// =====================================================
	// KNOWLEDGE GRAPH ANALYTICS QUERIES
	// =====================================================
	GetGraphStatistics(ctx context.Context, dollar_1 pgtype.UUID) (*GetGraphStatisticsRow, error)
	GetHighlyConnectedNodes(ctx context.Context, arg GetHighlyConnectedNodesParams) ([]*GetHighlyConnectedNodesRow, error)
	GetKnowledgeEdge(ctx context.Context, id pgtype.UUID) (*KnowledgeEdge, error)
	GetKnowledgeEdges(ctx context.Context, arg GetKnowledgeEdgesParams) ([]*GetKnowledgeEdgesRow, error)
	GetKnowledgeEvolution(ctx context.Context, arg GetKnowledgeEvolutionParams) ([]*KnowledgeEvolution, error)
	GetKnowledgeFlowNetwork(ctx context.Context, arg GetKnowledgeFlowNetworkParams) ([]*GetKnowledgeFlowNetworkRow, error)
	GetKnowledgeGraph(ctx context.Context, arg GetKnowledgeGraphParams) ([]*GetKnowledgeGraphRow, error)
	GetKnowledgeNode(ctx context.Context, id pgtype.UUID) (*KnowledgeNode, error)
	GetKnowledgeNodeByName(ctx context.Context, arg GetKnowledgeNodeByNameParams) (*KnowledgeNode, error)
	GetKnowledgeNodes(ctx context.Context, arg GetKnowledgeNodesParams) ([]*KnowledgeNode, error)
	GetKnowledgeReceptionStats(ctx context.Context, arg GetKnowledgeReceptionStatsParams) ([]*GetKnowledgeReceptionStatsRow, error)
	GetKnowledgeShare(ctx context.Context, id pgtype.UUID) (*GetKnowledgeShareRow, error)
	GetKnowledgeShares(ctx context.Context, arg GetKnowledgeSharesParams) ([]*GetKnowledgeSharesRow, error)
	GetKnowledgeSharesByCollaboration(ctx context.Context, dollar_1 pgtype.UUID) ([]*GetKnowledgeSharesByCollaborationRow, error)
	GetLearnedPattern(ctx context.Context, arg GetLearnedPatternParams) (*LearnedPattern, error)
	GetLearnedPatterns(ctx context.Context, arg GetLearnedPatternsParams) ([]*LearnedPattern, error)
	GetLearningEventStats(ctx context.Context, arg GetLearningEventStatsParams) (*GetLearningEventStatsRow, error)
	GetLearningEvents(ctx context.Context, arg GetLearningEventsParams) ([]*LearningEvent, error)
	GetLearningEventsByCorrelation(ctx context.Context, dollar_1 pgtype.UUID) ([]*LearningEvent, error)
	GetMemoriesByCausalLink(ctx context.Context, arg GetMemoriesByCausalLinkParams) ([]*EpisodicMemory, error)
	GetMemoriesByTemporalContext(ctx context.Context, arg GetMemoriesByTemporalContextParams) ([]*EpisodicMemory, error)
	// Analyzes memory access patterns for optimization
	GetMemoryAccessPatterns(ctx context.Context, userID pgtype.UUID) ([]*GetMemoryAccessPatternsRow, error)
	// Gets memory entries for a specific session with pagination
	GetMemoryEntriesBySession(ctx context.Context, arg GetMemoryEntriesBySessionParams) ([]*GetMemoryEntriesBySessionRow, error)
	// Gets all non-expired memory entries for a user
	GetMemoryEntriesByUser(ctx context.Context, userID pgtype.UUID) ([]*GetMemoryEntriesByUserRow, error)
	// Retrieves a memory entry by ID with explicit columns
	GetMemoryEntry(ctx context.Context, id pgtype.UUID) (*GetMemoryEntryRow, error)
	// Gets all relationships for a memory entry
	GetMemoryRelations(ctx context.Context, memoryID pgtype.UUID) ([]*GetMemoryRelationsRow, error)
	// Gets memory statistics grouped by type
	GetMemoryStats(ctx context.Context, userID pgtype.UUID) ([]*GetMemoryStatsRow, error)
	// =====================================================
	// PERFORMANCE AND MAINTENANCE QUERIES
	// =====================================================
	// Gets memory usage statistics for capacity planning
	GetMemoryUsageByUser(ctx context.Context, userID pgtype.UUID) (*GetMemoryUsageByUserRow, error)
	GetMessage(ctx context.Context, id pgtype.UUID) (*GetMessageRow, error)
	GetMessageCount(ctx context.Context, conversationID pgtype.UUID) (int64, error)
	GetMessagesByConversation(ctx context.Context, arg GetMessagesByConversationParams) ([]*GetMessagesByConversationRow, error)
	GetMessagesByRole(ctx context.Context, arg GetMessagesByRoleParams) ([]*GetMessagesByRoleRow, error)
	GetMostActiveWorkingMemory(ctx context.Context, arg GetMostActiveWorkingMemoryParams) ([]*WorkingMemory, error)
	GetMostConnectedNodes(ctx context.Context, arg GetMostConnectedNodesParams) ([]*GetMostConnectedNodesRow, error)
	GetMostEffectiveCollaborations(ctx context.Context, arg GetMostEffectiveCollaborationsParams) ([]*GetMostEffectiveCollaborationsRow, error)
	GetMostSharedKnowledge(ctx context.Context, arg GetMostSharedKnowledgeParams) ([]*GetMostSharedKnowledgeRow, error)
	GetMostUsedTools(ctx context.Context, arg GetMostUsedToolsParams) ([]*GetMostUsedToolsRow, error)
	GetNodeConnections(ctx context.Context, arg GetNodeConnectionsParams) ([]*GetNodeConnectionsRow, error)
	GetNodesByImportance(ctx context.Context, arg GetNodesByImportanceParams) ([]*KnowledgeNode, error)
	GetOptimalTeamCompositions(ctx context.Context, arg GetOptimalTeamCompositionsParams) ([]*GetOptimalTeamCompositionsRow, error)
	GetOrphanNodes(ctx context.Context, dollar_1 pgtype.UUID) ([]*KnowledgeNode, error)
	GetPatternEvolution(ctx context.Context, dollar_1 pgtype.UUID) ([]*GetPatternEvolutionRow, error)
	GetPatternStatistics(ctx context.Context, dollar_1 pgtype.UUID) (*GetPatternStatisticsRow, error)
	GetPopularPatterns(ctx context.Context, arg GetPopularPatternsParams) ([]*GetPopularPatternsRow, error)
	GetProceduralMemories(ctx context.Context, arg GetProceduralMemoriesParams) ([]*ProceduralMemory, error)
	GetProceduralMemory(ctx context.Context, id pgtype.UUID) (*ProceduralMemory, error)
	GetProductivityTrends(ctx context.Context, arg GetProductivityTrendsParams) ([]*GetProductivityTrendsRow, error)
	GetProjectionStatus(ctx context.Context, projectionName string) (*GetProjectionStatusRow, error)
	GetRecentAgentExecutions(ctx context.Context, arg GetRecentAgentExecutionsParams) ([]*AgentExecution, error)
	GetRecentChainExecutions(ctx context.Context, arg GetRecentChainExecutionsParams) ([]*ChainExecution, error)
	GetRecentChanges(ctx context.Context, arg GetRecentChangesParams) ([]*GetRecentChangesRow, error)
	GetRecentConversations(ctx context.Context, arg GetRecentConversationsParams) ([]*GetRecentConversationsRow, error)
	GetRecentEvents(ctx context.Context, arg GetRecentEventsParams) ([]*SystemEvent, error)
	GetRecentMessages(ctx context.Context, arg GetRecentMessagesParams) ([]*GetRecentMessagesRow, error)
	GetRecentToolExecutions(ctx context.Context, arg GetRecentToolExecutionsParams) ([]*ToolExecution, error)
	// Gets memory entries related to a given entry through relationships
	GetRelatedMemories(ctx context.Context, arg GetRelatedMemoriesParams) ([]*GetRelatedMemoriesRow, error)
	GetSemanticMemories(ctx context.Context, arg GetSemanticMemoriesParams) ([]*SemanticMemory, error)
	GetSemanticMemory(ctx context.Context, id pgtype.UUID) (*SemanticMemory, error)
	GetSemanticRelationships(ctx context.Context, arg GetSemanticRelationshipsParams) ([]*SemanticMemory, error)
	GetSessionStatistics(ctx context.Context, arg GetSessionStatisticsParams) (*GetSessionStatisticsRow, error)
	GetSkillProgression(ctx context.Context, arg GetSkillProgressionParams) (*GetSkillProgressionRow, error)
	GetSkillsByProficiency(ctx context.Context, arg GetSkillsByProficiencyParams) ([]*UserSkill, error)
	GetStrongestConnections(ctx context.Context, arg GetStrongestConnectionsParams) ([]*GetStrongestConnectionsRow, error)
	GetSystemEvent(ctx context.Context, id pgtype.UUID) (*SystemEvent, error)
	GetToolCacheByUser(ctx context.Context, arg GetToolCacheByUserParams) ([]*ToolCache, error)
	GetToolCacheEntry(ctx context.Context, arg GetToolCacheEntryParams) (*ToolCache, error)
	GetToolCacheStats(ctx context.Context, dollar_1 pgtype.UUID) (*GetToolCacheStatsRow, error)
	GetToolExecution(ctx context.Context, id pgtype.UUID) (*ToolExecution, error)
	GetToolExecutionCount(ctx context.Context, arg GetToolExecutionCountParams) (int32, error)
	GetToolExecutionTrends(ctx context.Context, arg GetToolExecutionTrendsParams) ([]*GetToolExecutionTrendsRow, error)
	GetToolExecutionsByMessage(ctx context.Context, messageID pgtype.UUID) ([]*ToolExecution, error)
	GetToolExecutionsByStatus(ctx context.Context, arg GetToolExecutionsByStatusParams) ([]*ToolExecution, error)
	GetToolExecutionsByTool(ctx context.Context, arg GetToolExecutionsByToolParams) ([]*ToolExecution, error)
	GetToolExecutionsByUser(ctx context.Context, arg GetToolExecutionsByUserParams) ([]*ToolExecution, error)
	GetToolUsageStats(ctx context.Context, userID pgtype.UUID) ([]*GetToolUsageStatsRow, error)
	GetToolUsageStatsByTool(ctx context.Context, arg GetToolUsageStatsByToolParams) (*GetToolUsageStatsByToolRow, error)
	GetTopSkills(ctx context.Context, arg GetTopSkillsParams) ([]*GetTopSkillsRow, error)
	GetUnprocessedEvents(ctx context.Context, limit int32) ([]*SystemEvent, error)
	GetUserActivitySummary(ctx context.Context, id pgtype.UUID) (*GetUserActivitySummaryRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error)
	GetUserContext(ctx context.Context, arg GetUserContextParams) (*UserContext, error)
	GetUserContextByType(ctx context.Context, arg GetUserContextByTypeParams) ([]*UserContext, error)
	// Combined analytics queries
	GetUserExecutionSummary(ctx context.Context, arg GetUserExecutionSummaryParams) (*GetUserExecutionSummaryRow, error)
	// User favorite tools
	GetUserFavoriteTools(ctx context.Context, id pgtype.UUID) ([][]byte, error)
	GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (*UserPreference, error)
	GetUserPreferencesByCategory(ctx context.Context, arg GetUserPreferencesByCategoryParams) ([]*UserPreference, error)
	// User API Keys related queries (to be implemented after migration)
	// User preferences and settings
	GetUserSettings(ctx context.Context, id pgtype.UUID) (*GetUserSettingsRow, error)
	GetUserSkill(ctx context.Context, arg GetUserSkillParams) (*UserSkill, error)
	GetUserSkills(ctx context.Context, arg GetUserSkillsParams) ([]*UserSkill, error)
	GetUserStatistics(ctx context.Context, id pgtype.UUID) (*GetUserStatisticsRow, error)
	GetWorkingMemory(ctx context.Context, arg GetWorkingMemoryParams) ([]*WorkingMemory, error)
	GetWorkingMemorySlot(ctx context.Context, arg GetWorkingMemorySlotParams) (*WorkingMemory, error)
	// Atomically increments access count and updates last access time
	IncrementMemoryAccess(ctx context.Context, id pgtype.UUID) error
	MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) (*SystemEvent, error)
	MarkEventProcessed(ctx context.Context, id pgtype.UUID) (*SystemEvent, error)
	// Maintenance query to update memory statistics
	OptimizeMemoryIndices(ctx context.Context) error
	OptimizeProcedure(ctx context.Context, arg OptimizeProcedureParams) (*ProceduralMemory, error)
	RecommendCollaborationPartners(ctx context.Context, arg RecommendCollaborationPartnersParams) ([]*RecommendCollaborationPartnersRow, error)
	RecordProjectionError(ctx context.Context, arg RecordProjectionErrorParams) (*EventProjection, error)
	RemoveFavoriteTool(ctx context.Context, arg RemoveFavoriteToolParams) (*RemoveFavoriteToolRow, error)
	ResetProjection(ctx context.Context, projectionName string) (*EventProjection, error)
	SearchCodePatterns(ctx context.Context, arg SearchCodePatternsParams) ([]*CodePattern, error)
	SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]*SearchConversationsRow, error)
	SearchEpisodicMemoriesBySimilarity(ctx context.Context, arg SearchEpisodicMemoriesBySimilarityParams) ([]*SearchEpisodicMemoriesBySimilarityRow, error)
	SearchKnowledgeNodesByName(ctx context.Context, arg SearchKnowledgeNodesByNameParams) ([]*KnowledgeNode, error)
	SearchKnowledgeNodesBySimilarity(ctx context.Context, arg SearchKnowledgeNodesBySimilarityParams) ([]*SearchKnowledgeNodesBySimilarityRow, error)
	// Searches memory entries with full-text search and filters
	SearchMemoryEntries(ctx context.Context, arg SearchMemoryEntriesParams) ([]*SearchMemoryEntriesRow, error)
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]*SearchMessagesRow, error)
	SearchPatternsByData(ctx context.Context, arg SearchPatternsByDataParams) ([]*LearnedPattern, error)
	SearchProceduralMemoriesByConditions(ctx context.Context, arg SearchProceduralMemoriesByConditionsParams) ([]*ProceduralMemory, error)
	SearchSemanticMemoriesBySimilarity(ctx context.Context, arg SearchSemanticMemoriesBySimilarityParams) ([]*SearchSemanticMemoriesBySimilarityRow, error)
	SearchSemanticMemoriesBySubject(ctx context.Context, arg SearchSemanticMemoriesBySubjectParams) ([]*SemanticMemory, error)
	SearchSimilarEmbeddings(ctx context.Context, arg SearchSimilarEmbeddingsParams) ([]*SearchSimilarEmbeddingsRow, error)
	SearchSimilarEmbeddingsAllTypes(ctx context.Context, arg SearchSimilarEmbeddingsAllTypesParams) ([]*SearchSimilarEmbeddingsAllTypesRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]*SearchUsersRow, error)
	UpdateAgentCapabilities(ctx context.Context, arg UpdateAgentCapabilitiesParams) (*AgentDefinition, error)
	UpdateAgentPerformance(ctx context.Context, arg UpdateAgentPerformanceParams) (*AgentDefinition, error)
	UpdateAutomationConfidence(ctx context.Context, arg UpdateAutomationConfidenceParams) (*ProceduralMemory, error)
	UpdateCollaborationExecution(ctx context.Context, arg UpdateCollaborationExecutionParams) (*AgentCollaboration, error)
	UpdateConversation(ctx context.Context, arg UpdateConversationParams) (*UpdateConversationRow, error)
	UpdateEmbedding(ctx context.Context, arg UpdateEmbeddingParams) (*Embedding, error)
	UpdateEpisodicMemoryAccess(ctx context.Context, id pgtype.UUID) (*EpisodicMemory, error)
	UpdateEpisodicMemoryImportance(ctx context.Context, arg UpdateEpisodicMemoryImportanceParams) (*EpisodicMemory, error)
	UpdateKnowledgeEdgeStrength(ctx context.Context, arg UpdateKnowledgeEdgeStrengthParams) (*KnowledgeEdge, error)
	UpdateKnowledgeNodeAccess(ctx context.Context, id pgtype.UUID) (*KnowledgeNode, error)
	UpdateKnowledgeNodeProperties(ctx context.Context, arg UpdateKnowledgeNodePropertiesParams) (*KnowledgeNode, error)
	UpdateKnowledgeShareAcceptance(ctx context.Context, arg UpdateKnowledgeShareAcceptanceParams) (*AgentKnowledgeShare, error)
	UpdateLearningEventFeedback(ctx context.Context, arg UpdateLearningEventFeedbackParams) (*LearningEvent, error)
	// Updates a memory entry with optimistic locking
	UpdateMemoryEntry(ctx context.Context, arg UpdateMemoryEntryParams) (*UpdateMemoryEntryRow, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (*UpdateMessageRow, error)
	UpdatePatternOutcome(ctx context.Context, arg UpdatePatternOutcomeParams) (*LearnedPattern, error)
	UpdatePatternQuality(ctx context.Context, arg UpdatePatternQualityParams) (*CodePattern, error)
	UpdatePatternUsage(ctx context.Context, arg UpdatePatternUsageParams) (*CodePattern, error)
	UpdateProceduralExecution(ctx context.Context, arg UpdateProceduralExecutionParams) (*ProceduralMemory, error)
	UpdateProjectionProgress(ctx context.Context, arg UpdateProjectionProgressParams) (*EventProjection, error)
	UpdateSemanticMemoryConfidence(ctx context.Context, arg UpdateSemanticMemoryConfidenceParams) (*SemanticMemory, error)
	UpdateSessionProgress(ctx context.Context, arg UpdateSessionProgressParams) (*DevelopmentSession, error)
	UpdateSkillRelatedPatterns(ctx context.Context, arg UpdateSkillRelatedPatternsParams) (*UserSkill, error)
	UpdateSkillUsage(ctx context.Context, arg UpdateSkillUsageParams) (*UserSkill, error)
	UpdateToolCacheHit(ctx context.Context, id pgtype.UUID) (*ToolCache, error)
	UpdateToolExecutionStatus(ctx context.Context, arg UpdateToolExecutionStatusParams) (*ToolExecution, error)
	UpdateUserContext(ctx context.Context, arg UpdateUserContextParams) (*UserContext, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (*UpdateUserPasswordRow, error)
	UpdateUserPreference(ctx context.Context, arg UpdateUserPreferenceParams) (*UserPreference, error)
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (*UpdateUserPreferencesRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (*UpdateUserProfileRow, error)
	UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (*UpdateUserSettingsRow, error)
	UpdateWorkingMemoryActivation(ctx context.Context, arg UpdateWorkingMemoryActivationParams) (*WorkingMemory, error)
	WeakenKnowledgeEdge(ctx context.Context, arg WeakenKnowledgeEdgeParams) (*KnowledgeEdge, error)
}

var _ Querier = (*Queries)(nil)
